//tealium universal tag - utag.555 ut4.0.202402200729, Copyright 2024 Tealium.com Inc. All Rights Reserved.
!function(w,d,t){w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e},ttq.load=function(e,n){var i="https://analytics.tiktok.com/i18n/pixel/events.js";ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=i,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};};}(window,document,'ttq');try{(function(id,loader){var u={'id':id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=='iframe'){m=a.getElementById(o.id);if(m&&m.tagName=='IFRAME'){b=m;}else{b=a.createElement('iframe');}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{'height':'1','width':'1','style':'display:none'},0);}else if(o.type=='img'){utag.DB('Attach img: '+o.src);b=new Image();}else{b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.async=1;b.charset='utf-8';}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute('src',o.src);if(typeof o.cb=='function'){if(b.addEventListener){b.addEventListener('load',function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb();}};}}if(o.type!='img'&&!m){l=o.loc||'head';c=a.getElementsByTagName(l)[0];if(c){utag.DB('Attach to '+l+': '+o.src);if(l=='script'){document.body.appendChild(b);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={'view':1,'link':1};u.scriptrequested=false;u.pixels_initialized={};u.clearEmptyKeys=function(object){Object.keys(object).forEach(function(key){if(object[key]===''||object[key]===undefined){delete object[key];}});return object;};u.forceBoolean=function(input){var bool;if(typeof input==='boolean'){bool=input;}else if(typeof input==='string'&&input.toLowerCase()==='true'){bool=true;}else{bool=false;}
return bool;};u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.sumItems=function(arr){var totalItems=0;arr.forEach(function(arrayItem){totalItems+=parseInt(arrayItem);});return totalItems;};u.map={"event_name:addToCart":"AddToCart","event_name:start_checkout":"InitiateCheckout","event_name:purchase":"PlaceAnOrder","order_id":"order_id","product_category":"product_category,content_category","product_unit_price":"product_unit_price","product_id":"product_id,content_name","order_currency":"order_currency","product_quantity":"product_quantity","product_sku_short":"content_id","facebook_content_type":"content_type"};u.extend=[function(a,b){try{if(1){if((utag.data.page_name_dr==="ThreePgCheckoutAddressPaymentInfoPage"&&(utag.data.page_name.indexOf("Billing")>-1))||(utag.data.page_name.indexOf("Shipping")>-1)){setTimeout(function(){var totalOrderValue=0;if(typeof utag.data.product_unit_price!=='undefined'){totalOrderValue=Number(utag.data.order_price_minus_discount);}
var addProductCount=utag.data.product_sku_short.length||1;var contentArray=[];for(var dex=0;dex<addProductCount;dex++){var sku=(dex<utag.data.product_sku_short.length)?utag.data.product_sku_short[dex]:"0";var name=(dex<utag.data.product_id.length)?utag.data.product_id[dex]:"";var price=(dex<utag.data.product_unit_price.length)?utag.data.product_unit_price[dex]:"0";var quantity=(dex<utag.data.product_quantity.length)?utag.data.product_quantity[dex]:"1";var content={content_name:name,content_id:sku,content_type:'product_group',quantity:quantity,price:price,}
contentArray.push(content);}
ttq.track('InitiateCheckout',{contents:contentArray,value:totalOrderValue,currency:'USD'});},2000);}
if(((utag.data.page_name=='Payment')||$('#dr_CheckoutStep2').is(':visible'))||(window.location.href.indexOf("stage=payment")>-1)){setTimeout(function(){var totalOrderValue=0;if(typeof utag.data.order_subtotal!=='undefined'){totalOrderValue=Number(utag.data.order_subtotal);}
var addProductCount=utag.data.product_sku_short.length||1;var contentArray=[];for(var dex=0;dex<addProductCount;dex++){var sku=(dex<utag.data.product_sku_short.length)?utag.data.product_sku_short[dex]:"0";var name=(dex<utag.data.product_id.length)?utag.data.product_id[dex]:"";var price=(dex<utag.data.product_unit_price.length)?utag.data.product_unit_price[dex]:"0";var quantity=(dex<utag.data.product_quantity.length)?utag.data.product_quantity[dex]:"1";var content={content_name:name,content_id:sku,content_type:'product_group',quantity:quantity,price:price,}
contentArray.push(content);}
ttq.track('PlaceAnOrder',{contents:contentArray,value:totalOrderValue,currency:'USD'});},2000);}
jQuery('body').on('mousedown','.buy-opt,.js-addToCartBtn,.js-add-to-cart,.addToCart',function(e){if((typeof jQuery(this).attr('data-analytics-product-name')!=='undefined'))
var prodId=jQuery(this).attr('data-analytics-product-name').length?jQuery(this).attr('data-analytics-product-name'):"";var prodPrice=jQuery(this).attr('data-analytics-product-list-price').length?jQuery(this).attr('data-analytics-product-list-price'):0;prodPrice=Number(prodPrice.replace(/[^0-9\.-]+/g,""));if((typeof jQuery(this).attr('data-analytics-product-sku-short')!=='undefined'))
var prodsku=jQuery(this).attr('data-analytics-product-sku-short').length?jQuery(this).attr('data-analytics-product-sku-short'):utag.data.product_sku_short;else
var prodsku="";ttq.track('AddToCart',{content_name:(typeof utag.data.product_id!=='undefined')?utag.data.product_id.toString():prodId,content_category:(typeof utag.data.product_category!=='undefined')?utag.data.product_category.toString():"0",content_id:prodsku.length?prodsku.toString():"0",content_type:'product_group',quantity:1,value:prodPrice,currency:'USD'});});jQuery('body').on('mousedown','.js-bundles-atc-btn',function(e){if((typeof jQuery(this).attr('data-analytics-product-name')!=='undefined'))
var prodId=jQuery(this).attr('data-analytics-product-name').length?jQuery(this).attr('data-analytics-product-name'):"";if((typeof jQuery('.bundle-price.js-bundle-price')!=='undefined'))
var prodPrice=jQuery('.bundle-price.js-bundle-price').length?(jQuery('.bundle-price.js-bundle-price').text()).replace("$","").replace(",",""):0;else
var prodPrice=jQuery(this).attr('data-analytics-product-list-price').length?jQuery(this).attr('data-analytics-product-list-price'):0;if(prodPrice.indexOf('-')>-1)
prodPrice=0;else
prodPrice=Number(prodPrice.replace(/[^0-9\.-]+/g,""));if((typeof jQuery(this).attr('data-analytics-product-short-sku')!=='undefined'))
var prodsku=jQuery(this).attr('data-analytics-product-short-sku').length?jQuery(this).attr('data-analytics-product-short-sku'):"";else
var prodsku="";ttq.track('AddToCart',{content_name:(typeof utag.data.product_id!=='undefined')?utag.data.product_id.toString():prodId,content_category:(typeof utag.data.product_category!=='undefined')?utag.data.product_category.toString():"0",content_id:prodsku.length?prodsku.toString():"0",content_type:'product_group',quantity:1,value:prodPrice,currency:'USD'});});if(((utag.data.page_type=='PDP'||utag.data.page_type=='detail')||(window.location.href.indexOf("/products/")>-1))&&typeof utag.data.product_id!=='undefined'&&utag.data.page_type!=='ShoppingCart'&&typeof utag.data.dockedCartView=='undefined'){setTimeout(function(){ttq.track('ViewContent',{content_name:(typeof utag.data.product_id!=='undefined')?utag.data.product_id.toString():"",content_category:(typeof utag.data.product_category!=='undefined')?utag.data.product_category.toString():"",content_id:(typeof utag.data.product_sku_short!=='undefined')?utag.data.product_sku_short.toString():"0",content_type:'product_group',value:0,currency:'USD'});},2000);}
if((utag.data.order_id!==undefined)){setTimeout(function(){var totalOrderValue=0;if(typeof utag.data.product_unit_price!=='undefined'){totalOrderValue=Number(utag.data.order_price_minus_discount);}
var addProductCount=utag.data.product_sku_short.length||1;var contentArray=[];for(var dex=0;dex<addProductCount;dex++){var sku=(dex<utag.data.product_sku_short.length)?utag.data.product_sku_short[dex]:"0";var name=(dex<utag.data.product_id.length)?utag.data.product_id[dex]:"";var price=(dex<utag.data.product_unit_price.length)?utag.data.product_unit_price[dex]:"0";var quantity=(dex<utag.data.product_quantity.length)?utag.data.product_quantity[dex]:"1";var content={content_name:name,content_id:sku,content_type:'product_group',quantity:quantity,price:price,}
contentArray.push(content);}
ttq.identify({email:utag.data.customer_emailid.length?utag.data.customer_emailid:"",phone_number:'',});ttq.track('CompletePayment',{contents:contentArray,value:totalOrderValue,currency:'USD'});},2000);}}}catch(e){utag.DB(e)}}];u.handleEvent=function(event_name){if(!event_name){return;}
var param,event_data={};event_data.description=u.data.description;event_data.search_string=u.data.search_string;event_data.success=u.data.success;if(event_name!=='Pageview'){event_data.currency=u.data.currency||u.data.order_currency;event_data.item_category=u.data.item_category||u.data.product_category;event_data.item_ids=u.data.item_ids||u.data.product_id;event_data.number_items=u.data.number_items||u.sumItems(u.data.product_quantity);event_data.payment_info_available=u.data.payment_info_available;event_data.price=u.data.price||u.data.order_subtotal;event_data.sign_up_method=u.data.sign_up_method;event_data.transaction_id=u.data.transaction_id||u.data.order_id;event_data.content_category=u.data.content_category;event_data.content_name=u.data.content_name;event_data.content_id=u.data.content_id;event_data.value=u.data.value;event_data.quantity=u.data.quantity;event_data.query=u.data.query;event_data.content_type=u.data.content_type;event_data.customer_id=u.data.customer_id;event_data.product_unit_price=u.data.product_unit_price;event_data.contents=u.data.contents;}
window.ttq.track(event_name,u.clearEmptyKeys(event_data));};u.send=function(utag_event,data_layer){if(u.ev[utag_event]||u.ev.all!==undefined){utag.DB('send:555');utag.DB(data_layer);var a,b,c,f,i,pixel_list,query_params;a=utag_event;b=data_layer;u.data={base_url:'https://analytics.tiktok.com/i18n/pixel/events.js?sdkid=C9LF8BJC77UEMUC6P5LG&lib=ttq',pixel_code:'C9LF8BJC77UEMUC6P5LG',content_type:'product',auto_page_tracking:true,auto_purchase_tracking:true,email:'',phone_number:'',sha256_email:'',sha256_phone_number:'',currency:'',content_category:'',content_name:'',content_id:'',value:0,quantity:'',price:null,query:'',contents:[],order_id:'',order_subtotal:'',order_currency:'',customer_id:'',product_id:[],product_category:[],product_quantity:[],product_unit_price:[],event:[],user_data:{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB('send:555:EXTENSIONS');utag.DB(data_layer);c=[];Object.keys(utag.loader.GV(u.map)).forEach(function(mapping_key){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==''){var destinations=u.map[mapping_key].split(',');destinations.forEach(function(parameter){if(parameter==='email'||parameter==='phone_number'||parameter==='sha256_email'||parameter==='sha256_phone_number'){u.data.user_data[parameter]=data_layer[mapping_key];}else if(u.data.hasOwnProperty(parameter)||parameter.indexOf('.')>-1){u.map_func(parameter.split('.'),u.data,data_layer[mapping_key]);}});}else{var event_destinations=mapping_key.split(':');if(event_destinations.length===2&&String(data_layer[event_destinations[0]])===String(event_destinations[1])){if(u.map[mapping_key]){u.data.event=u.data.event.concat(u.map[mapping_key].split(","));}}}});utag.DB('send:555:MAPPINGS');utag.DB(u.data);var eCommerceMapping=[{eCommerceData:b._corder,name:'order_id',isArray:false},{eCommerceData:b._csubtotal,name:'order_subtotal',isArray:false},{eCommerceData:b._ccurrency,name:'order_currency',isArray:false},{eCommerceData:b._ccustid,name:'customer_id',isArray:false},{eCommerceData:b._cprod,name:'product_id',isArray:true},{eCommerceData:b._ccat,name:'product_category',isArray:true},{eCommerceData:b._cquan,name:'product_quantity',isArray:true},{eCommerceData:b._cprice,name:'product_unit_price',isArray:true},];eCommerceMapping.forEach(function(dataObject){if(!dataObject.isArray){u.data[dataObject.name]=u.data[dataObject.name]||dataObject.eCommerceData||'';}else if(u.data[dataObject.name].length===0&&dataObject.eCommerceData!==undefined&&dataObject.isArray){u.data[dataObject.name]=dataObject.eCommerceData.slice(0);}});if(u.data.event.length===0&&b._cevent!==undefined){u.data.event=(u.typeOf(b._cevent)==='array')?b._cevent.slice(0):[b._cevent];}
if(u.data.contents.length>0){u.data.contents.forEach(function(element){u.data.value+=parseInt(element.price);});}
if(u.data.product_unit_price.length>0){u.data.product_unit_price.forEach(function(price){u.data.value+=price;});}
if(!u.data.pixel_code){utag.DB(u.id+': Tag not fired: Required attribute pixel_code not populated');return;}
pixel_list=u.data.pixel_code.split(',');pixel_list.forEach(function(pixel){if(!u.pixels_initialized[pixel]){window.ttq.load(u.data.pixel_code);window.ttq.identify(u.data.user_data);u.pixels_initialized[pixel]=true;}});if(u.forceBoolean(u.data.auto_page_tracking)&&a==='view'){window.ttq.page();}
if(u.data.event.join(',').indexOf('PlaceAnOrder')===-1&&u.data.order_id&&u.forceBoolean(u.data.auto_purchase_tracking)){u.data.event.push('PlaceAnOrder');}
u.data.event.forEach(function(e){u.handleEvent(e);});if(!u.scriptrequested){u.scriptrequested=true;u.loader({type:'script',src:u.data.base_url,cb:null,loc:'script',id:'utag_555',attrs:{}});}
utag.DB('send:555:COMPLETE');}};utag.o[loader].loader.LOAD(id);}('555','logitech.g'));}catch(error){utag.DB(error);}
